---
abstract: 'Regional context SMS::Send driver to send messages via Unicel Technologies (http://unicel.in/)'
author:
  - 'Indranil Das Gupta <indradg@l2c2.co.in>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMS-Send-IN-Unicel
no_index:
  directory:
    - t
requires:
  File::Spec: 3.33
  IO::Socket::SSL: 1.76
  LWP::UserAgent: 6.04
  SMS::Send: 1.06
  Test::Exception: 0.31
  Test::More: 0.98
version: 0.01
